apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallet-api.fullname" . }}-common
data:
 chain-id: {{ default "" .Values.config.common.chainId | quote }}
 ethereum-backend-host: {{ default "" .Values.config.common.ethereumBackendHost | quote }}
 polygon-backend-host: {{ default "" .Values.config.common.polygonBackendHost | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallet-api.fullname" . }}-aws
data:
  aws-wallet-create-notification-queue-name: {{ default "" .Values.config.aws.walletCreateNotificationQueueName | quote }}
  aws-wallet-create-notification-queue-url: {{ default "" .Values.config.aws.walletCreateNotificationQueueUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallet-api.fullname" . }}-jwt
data:
 jwt-expires-in: {{ default "" .Values.config.jwt.expiresIn | quote }}

