apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-database
type: Opaque
data:
  host: {{ default "" .Values.secret.database.host | b64enc | quote }}
  user: {{ default "" .Values.secret.database.user | b64enc | quote }}
  port: {{ default "" .Values.secret.database.port | b64enc | quote }}
  password: {{ default "" .Values.secret.database.password | b64enc | quote }}
  database: {{ default "" .Values.secret.database.database | b64enc | quote }}
  engine: {{ default "" .Values.secret.database.engine | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-aws
type: Opaque
data:
  aws-region: {{ default "" .Values.secret.aws.awsRegion | b64enc | quote }}
  aws-access-key: {{ default "" .Values.secret.aws.awsAccessKey | b64enc | quote }}
  aws-secret-key: {{ default "" .Values.secret.aws.awsSecretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-oauth
data:
  oauth2-token-expires-in-password: {{ default "" .Values.secret.oauth.oauth2TokenExpiresInPassword | b64enc | quote }}
  oauth2-refresh-token-expires-in: {{ default "" .Values.secret.oauth.oauth2RefreshTokenExpiresIn | b64enc | quote }}
  secret-key: {{ default "" .Values.secret.oauth.secretKey | b64enc | quote }}
  reset-pin-jwt-exp: {{ default "" .Values.secret.oauth.resetPinJwtExp | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-identity
data:
  identity-danal-cpid: {{ default "" .Values.secret.identity.identityDanalCPID | b64enc | quote }}
  identity-danal-cppwd: {{ default "" .Values.secret.identity.identityDanalCPPWD | b64enc | quote }}
  identity-encrypt-key: {{ default "" .Values.secret.identity.identityEncryptKey | b64enc | quote }}
  identity-valid-redirect-urls: {{ default "" .Values.secret.identity.identityValidRedirectUrls | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-social
data:
  social-login-apple-app-id: {{ default "" .Values.secret.social.socialLoginAppleAppId | b64enc | quote }}


