apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "originals.fullname" . }}
data:
  ethereumBackendHost: {{ default "" .Values.config.backend.ethereumBackendHost | quote }}
  polygonBackendHost: {{ default "" .Values.config.backend.polygonBackendHost | quote }}
