---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "originals.fullname" . }}-database
type: Opaque
data:
  host: {{ default "" .Values.secret.database.host | b64enc | quote }}
  engine: {{ default "" .Values.secret.database.engine | b64enc | quote }}
  database: {{ default "" .Values.secret.database.database | b64enc | quote }}
  password: {{ default "" .Values.secret.database.password | b64enc | quote }}
  port: {{ default "" .Values.secret.database.port | b64enc | quote }}
  user: {{ default "" .Values.secret.database.user | b64enc | quote }}
  poolSize: {{ default "" .Values.secret.database.poolSize | b64enc | quote }}
  migrateRun: {{ default "" .Values.secret.database.migrateRun | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "originals.fullname" . }}-alchemy
type: Opaque
data:
  ethereumHost: {{ default "" .Values.secret.alchemy.ethereumHost | b64enc | quote }}
  ethereumApiKey: {{ default "" .Values.secret.alchemy.ethereumApiKey | b64enc | quote }}
  polygonHost: {{ default "" .Values.secret.alchemy.polygonHost | b64enc | quote }}
  polygonApiKey: {{ default "" .Values.secret.alchemy.polygonApiKey | b64enc | quote }}
